### ISSUE TITLE
android上扫描完就崩了

### ISSUE THREAD

**Issue by kazeik** [yxwandroid/flutter_plugin_qrcode#3]
java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime(25340): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4349)
E/AndroidRuntime(25340): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4392)
E/AndroidRuntime(25340): 	at android.app.ActivityThread.-wrap22(ActivityThread.java)
E/AndroidRuntime(25340): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635)
E/AndroidRuntime(25340): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime(25340): 	at android.os.Looper.loop(Looper.java:156)
E/AndroidRuntime(25340): 	at android.app.ActivityThread.main(ActivityThread.java:6623)
E/AndroidRuntime(25340): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25340): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
E/AndroidRuntime(25340): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
E/AndroidRuntime(25340): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime(25340): 	at flutterplugin.accs.com.flutter_plugin_qrcode.FlutterPluginQrcodePlugin.onActivityResult(FlutterPluginQrcodePlugin.java:63)
E/AndroidRuntime(25340): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:634)
E/AndroidRuntime(25340): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:367)
E/AndroidRuntime(25340): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:546)
E/AndroidRuntime(25340): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:594)
E/AndroidRuntime(25340): 	at android.app.Activity.dispatchActivityResult(Activity.java:7188)
E/AndroidRuntime(25340): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4345)
E/AndroidRuntime(25340): 	... 9 more
I/Process (25340): Sending signal. PID: 25340 SIG: 9

**Comment by Quantriple** [comment]
我也是  尴尬了

**Comment by yxwandroid** [comment]
请使用最新版本2.0.0
