### ISSUE TITLE
ios打开报错

### ISSUE THREAD

**Issue by mengsiyitiaojie** [yxwandroid/flutter_plugin_qrcode#4]
![image](https://user-images.githubusercontent.com/55568326/88496001-5563ee80-cfee-11ea-9289-79bb387e8f20.png)
![image](https://user-images.githubusercontent.com/55568326/88496010-5d239300-cfee-11ea-8c20-5732323e5540.png)
![image](https://user-images.githubusercontent.com/55568326/88496218-0cf90080-cfef-11ea-812a-84ff9ced8768.png)

**Comment by mengsiyitiaojie** [comment]
![Uploading image.png…]

**Comment by yxwandroid** [comment]
请使用最新的xcode 打开example 项目    看看能否运行 刚我更新了一下最新版本 v2.0.0 你可以先试试
