### ISSUE TITLE
2.0版本IOS打包出现问题

### ISSUE THREAD

**Issue by fuyixiazhang** [yxwandroid/flutter_plugin_qrcode#7]
Xcode's output:
↳
    /users/fuyixiazhang/documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/fl
    utter_plugin_qrcode-2.0.0/ios/Classes/ACScanViewController.swift:206:14:
    error: 'bringSubview(toFront:)' has been renamed to
    'bringSubviewToFront(_:)'
            view.bringSubview(toFront: self.animalLine)
                 ^~~~~~~~~~~~ ~~~~~~~~~
                 bringSubviewToFront 
    UIKit.UIView:17:15: note: 'bringSubview(toFront:)' was obsoleted in Swift
    4.2
        open func bringSubview(toFront view: UIView)
                  ^
    /users/fuyixiazhang/documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/fl
    utter_plugin_qrcode-2.0.0/ios/Classes/ACScanViewController.swift:231:61:
    error: 'commonModes' has been renamed to 'RunLoop.Mode.common'
            RunLoop.main.add(self.timer!, forMode: RunLoop.Mode.commonModes)
                                                                ^~~~~~~~~~~
                                                                RunLoop.Mode.com
                                                                mon
    Foundation.RunLoop.Mode:9:23: note: 'commonModes' was obsoleted in Swift 4.2
        public static let commonModes: RunLoop.Mode
                          ^
    /users/fuyixiazhang/documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/fl
    utter_plugin_qrcode-2.0.0/ios/Classes/ACScanViewController.swift:206:14:
    error: 'bringSubview(toFront:)' has been renamed to
    'bringSubviewToFront(_:)'
            view.bringSubview(toFront: self.animalLine)
                 ^~~~~~~~~~~~ ~~~~~~~~~
                 bringSubviewToFront 
    UIKit.UIView:17:15: note: 'bringSubview(toFront:)' was obsoleted in Swift
    4.2
        open func bringSubview(toFront view: UIView)
                  ^
    /users/fuyixiazhang/documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/fl
    utter_plugin_qrcode-2.0.0/ios/Classes/ACScanViewController.swift:231:61:
    error: 'commonModes' has been renamed to 'RunLoop.Mode.common'
            RunLoop.main.add(self.timer!, forMode: RunLoop.Mode.commonModes)
                                                                ^~~~~~~~~~~
                                                                RunLoop.Mode.com
                                                                mon
    Foundation.RunLoop.Mode:9:23: note: 'commonModes' was obsoleted in Swift 4.2
        public static let commonModes: RunLoop.Mode
                          ^
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Encountered error while building for device.

**Comment by yxwandroid** [comment]
error: 'bringSubview(toFront:)' has been renamed to
'bringSubviewToFront(:)'
view.bringSubview(toFront: self.animalLine)
^~~~~~~~~~~~ ~~~~~~~~~
bringSubviewToFront
UIKit.UIView:17:15: note: 'bringSubview(toFront:)' was obsoleted in Swift
4.2
你for下来修改一下
